# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-11-26 17:27:15
"""
#Importing the arcpy library for working with GIS data
import arcpy

def Model1():  # Model1

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Input feature classes
    ONT_WSHED_BDRY_SEC_DERIVED = "ONT_WSHED_BDRY_SEC_DERIVED"
    Fishing_Access_Point = "Fishing_Access_Point"

    # Step 1: Create a buffer around the fishing access points
    # Process: Buffer (Buffer) (analysis)
    fishing_Buffer1 = "C:\\Users\\A00170676\\OneDrive - Canadore College\\Desktop\\GEO Sem 1\\GEO115\\Assignment_9 Wk_7\\Assgn 9\\Assgn 9\\Assgn 9.gdb\\fishing_Buffer1"
    # Buffering fishing access points with a distance of 20 kilometers
    # The "dissolve_option" parameter ensures that overlapping buffers are merged into one
    arcpy.analysis.Buffer(in_features=Fishing_Access_Point, out_feature_class=fishing_Buffer1, buffer_distance_or_field="20 Kilometers", dissolve_option="ALL")

    # Step 2: Intersect the buffer with the watershed boundary dataset
    gpr_000b11a_e_Intersect = "C:\\Users\\A00170676\\OneDrive - Canadore College\\Desktop\\GEO Sem 1\\GEO115\\Assignment_9 Wk_7\\Assgn 9\\Assgn 9\\Assgn 9.gdb\\gpr_000b11a_e_Intersect"
    # Setting the environment extent to the buffer output
    # This ensures that the intersect process only considers the buffered area
    with arcpy.EnvManager(extent=fishing_Buffer1):
        arcpy.analysis.Intersect(in_features=[[ONT_WSHED_BDRY_SEC_DERIVED, ""], [fishing_Buffer1, ""]], out_feature_class=gpr_000b11a_e_Intersect)
    
    # Step 3: Clip the intersect result to a specific area of interest
    # Define the output path for the clipped data
    clipped_output = "C:\\Users\\A00170676\\OneDrive - Canadore College\\Desktop\\GEO Sem 1\\GEO115\\Assignment_9 Wk_7\\Assgn 9\\Assgn 9\\Assgn 9.gdb\\clipped_output"

if __name__ == '__main__':
    # Setting global environment workspaces for scratch and current geodatabase
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\A00170676\\OneDrive - Canadore College\\Desktop\\GEO Sem 1\\GEO115\\Assignment_9 Wk_7\\Assgn 9\\Assgn 9\\Assgn 9.gdb", workspace="C:\\Users\\A00170676\\OneDrive - Canadore College\\Desktop\\GEO Sem 1\\GEO115\\Assignment_9 Wk_7\\Assgn 9\\Assgn 9\\Assgn 9.gdb"):
        # Running the model function
        Model1()
